apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: nginx
  name: nginx
spec: 
  type: LoadBalancer
   externalIPs:
  - 192.16.35.12
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector: 
    app: nginx