apiVersion: apps/v1
kind: Deployment
metadata:
  name: reduser-deploy
  labels:
    app: reduser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reduser
  template:
    metadata:
      labels:
        app: reduser
    spec:
      containers:
      - name: reduser
        image: kourse/reduser-env_redis:v0.1.0
        env:
        - name: REDIS_POD_IP
          value: "REDIS_POD_IP"
        ports:
        - containerPort: 3000
