apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  externalIPs:
  - 172.22.132.10
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
