apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: tcpdump-ds
  labels:
    app: tcpdump
spec:
  selector:
    matchLabels:
      app: tcpdump
  template:
    metadata:
      labels:
        app: tcpdump
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: tcpdump-container
        image: kourse/tcp-nc:v0.1.0
        imagePullPolicy: Always
        command: 
        - "/bin/bash"
        - "-c"
        - "tcpdump -s 0 -#U -w - | nc <nc-svc-ip> 8080"

